# Generated by Django 5.1.3 on 2024-11-14 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
                ('translation', models.CharField(max_length=100)),
                ('transcription', models.CharField(max_length=100)),
                ('topic', models.CharField(max_length=50)),
            ],
        ),
    ]
