# Generated by Django 5.1.3 on 2024-11-24 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0002_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='flashcards.topic'),
        ),
    ]
