# Generated by Django 5.1.3 on 2024-12-11 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0007_userprogress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercardprogress',
            name='correct_streak',
        ),
        migrations.RemoveField(
            model_name='usercardprogress',
            name='mistakes',
        ),
        migrations.RemoveField(
            model_name='usercardprogress',
            name='total_attempts',
        ),
        migrations.AlterField(
            model_name='usercardprogress',
            name='status',
            field=models.CharField(choices=[('learned', 'Выучено'), ('needs_review', 'Нуждается в повторении'), ('not_learned', 'Не выучено')], default='not_learned', max_length=20),
        ),
        migrations.DeleteModel(
            name='UserProgress',
        ),
    ]
