# Generated by Django 5.1.3 on 2024-12-11 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0008_remove_usercardprogress_correct_streak_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercardprogress',
            name='correct_streak',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usercardprogress',
            name='mistakes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usercardprogress',
            name='total_attempts',
            field=models.IntegerField(default=0),
        ),
    ]
